# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# my web title and email
title: NaicenLee
email: 3097347965@qq.com

# page footer description
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to NaicenLee personal home page. Here is Karry Lee personal diary and some articles. 
baseurl: "" # the subpath of your site, e.g. /blog

# this stop write
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: undefault
github_username:  naicenlee
#facebook_username: KarryLee

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#This basic address setting has been so important for me for two days.
#After setting this address, you need to use the base address to access it locally.
#baseurl: https://laveyem.github.io/KarryLee/
#baseurl: /KarryLee
